import { KPICard } from "./components";

import { kpiData02, kpiData01 } from "@/../mocks/kpiDataMocks";
import { CardsGroup } from "@/components";
import useSearchAssetsByName from "@/hooks/useSearchAssetsByName";
import { KPI } from "@/global/types";

const KPIContent = () => {
  const filterDataBySearch = useSearchAssetsByName<KPI>();

  return (
    <div className="flex flex-col gap-6">
      <CardsGroup
        title="Revenue"
        description="Measures the total revenue generated by the business each month."
        data={filterDataBySearch(kpiData01)}
        CardComponent={KPICard}
      />
      <CardsGroup
        title="Sales"
        description="Measures the total sales generated by the business each month."
        data={filterDataBySearch(kpiData02)}
        CardComponent={KPICard}
      />
    </div>
  );
};

export default KPIContent;
